algoritmo "34"

var
 N1,N2,N3:real
 MEDIA:real

inicio
      ESCREVAL ("================")
      ESCREVAL ("MEDIA de 3 NOTAS")
      ESCREVAL ("================")
      ESCREVAL ("")
      ESCREVA ("DIGITE NOTA 1: ")
      LEIA (N1)
      ESCREVA ("DIGITE NOTA 2: ")
      LEIA (N2)
      ESCREVA ("DIGITE NOTA 3: ")
      LEIA (N3)
      MEDIA <- (N1 + N2 + N3) /3
      ESCREVAL("VALOR DA MEDIA: ",MEDIA)

Fimalgoritmo