algoritmo "01-Subtração entre numeros"

var
   N1,N2,R:inteiro

inicio
      ESCREVAL ("-----------------------")
      ESCREVAL ("SUBTRAÇÃO ENTRE NUMEROS")
      ESCREVAL ("-----------------------")
      ESCREVA ("DIGITE UM NUMERO: ")
      LEIA (N1)
      ESCREVA ("DIGITE OUTRO NUMERO: ")
      LEIA (N2)
      R <- N1-N2
      ESCREVA ("A SUBTRAÇÃO ENTRE OS NUMEROS: ")
      ESCREVA (R)
      ESCREVAL ("")

fimalgoritmo